name: book_manager_$ENVIRONMENT
services:
  app:
    container_name: book_manager_app
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    env_file: .env
    build: .
    volumes:
      - ..:/app
    ports:
      - "80:8000"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - db
    networks:
      - book_manager_network

  db:
    container_name: book_manager_db
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "$EXTERNAL_PORT_POSTGRES:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - book_manager_network

  adminer:
    container_name: book_manager_adminer
    image: adminer
    restart: always
    ports:
      - $EXTERNAL_PORT_ADMINER:8080
    networks:
      - book_manager_network

networks:
  book_manager_network:
    driver: bridge

volumes:
  db_data:
    driver: local
