name: book_manager_$ENVIRONMENT
services:
  app:
    build:
      dockerfile: ./dev_environment/Dockerfile
      context: ../
    container_name: book_manager_app
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    env_file: .env
    volumes:
      - ..:/app
    ports:
      - $APP_EXTERNAL_PORT:8000
    environment:
      - TZ=$TZ
    depends_on:
      - db
    networks:
      - book_manager_network

  db:
    container_name: book_manager_db
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - TZ=$TZ
    networks:
      - book_manager_network

  adminer:
    container_name: book_manager_adminer
    image: adminer
    restart: always
    ports:
      - $EXTERNAL_PORT_ADMINER:8080
    networks:
      - book_manager_network

networks:
  book_manager_network:
    driver: bridge

volumes:
  db_data:
    driver: local
