# Generated by Django 5.2.1 on 2025-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the author's name",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="Enter the author's nationality",
                        max_length=100,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Enter the author's birth date",
                        null=True,
                        verbose_name="Birth Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the book",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a brief description of the book",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "pub_year",
                    models.PositiveIntegerField(
                        help_text="Enter the year the book was published",
                        verbose_name="Publication Year",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Enter the genre of the book",
                        max_length=100,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        help_text="Select the author(s) of the book",
                        related_name="books",
                        to="database.author",
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
    ]
