name: ${APP_NAME}_$ENVIRONMENT
services:
  
  db:
    container_name: ${APP_NAME}_db_$ENVIRONMENT
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - ceragon_library_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TZ=$TZ
    networks:
      - ceragon_library_network_prod
  app:
      build:
        dockerfile: ./prod/base/Dockerfile
        context: ../
      container_name: ${APP_NAME}_app_$ENVIRONMENT
      working_dir: /app
      tty: true
      stdin_open: true
      restart: always
      env_file: .env
      volumes:
        - static_volume:/app/staticfiles
        - ../logs:/logs
      environment:
        - TZ=$TZ
      depends_on:
        - db
      networks:
        - ceragon_library_network_prod
      
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx_$ENVIRONMENT
    ports:
      - "$APP_EXTERNAL_PORT:80"
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - ceragon_library_network_prod

networks:
  ceragon_library_network_prod:
    driver: bridge

volumes:
  ceragon_library_data_prod:
    driver: local
  static_volume:
